app:
  logLevel: LOG_LEVEL
  logsDir: APP_LOGS_DIR
  appEnv: APP_ENV
  apiKey: METIS_API_KEY
  datadogApiKey: DATADOG_API_KEY
  sentryDsn: SENTRY_DSN
http:
  scheme: HTTP_SCHEME
  url: HTTP_URL
  port: HTTP_PORT
