app:
  logLevel: LOG_LEVEL
  prettyPrint: LOG_PRETTY_PRINT
  logsDir: APP_LOGS_DIR
  appEnv: APP_ENV
  apiKey: METIS_API_KEY
  datadogApiKey: DATADOG_API_KEY
  sentryDsn: SENTRY_DSN
processor:
  bufferInMs: METIS_PROCESSOR_BUFFER_IN_MS
  maxItemsInBulk: METIS_PROCESSOR_BULK_MAX_ITEMS
http:
  scheme: METIS_HTTP_SCHEME
  url: METIS_HTTP_URL
  port: METIS_HTTP_PORT
