name: Lint and test

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false


    steps:
      - uses: actions/checkout@v2

     - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - run: npm install
      - run: npm i --save-dev esbuild
      - run: npm run test
      - run: npm run lint
      - run: npm run build-all
